### ISSUE TITLE
Waterdog (Proxy-Master-1) won't start on Cloud Startup

### ISSUE THREAD

**Issue by CallMeYuuuu** [BedrockCloud/CloudSystem#3]
start.sh: `screen -S mcpe-cloud java -jar -Xms512M -Xmx1G BedrockCloud.jar`

![image](https://user-images.githubusercontent.com/44119696/195332465-8fd40616-706c-47ad-be48-ec9ec26c54df.png)
Thats everything it shows

and `/cloud/templates/Proxy-Master/ is empty`

**Comment by CallMeYuuuu** [comment]
Topic change: No feedback if server successfully started... please fix

**Comment by xxFLORII** [comment]
do you have uploaded cloudbridge-wd into local/plugins/waterdogpe and cloudbridge-pm into local/plugins/pocketmine?

**Comment by CallMeYuuuu** [comment]
No but it also doesn't say anywhere that these plugins are required

**Comment by xxFLORII** [comment]
ig i will add an auto downloader for the plugins this weekend

**Comment by CallMeYuuuu** [comment]
And a Setup documentation would also be cool

**Comment by xxFLORII** [comment]
> ig i will add an auto downloader for the plugins this weekend

Implemented in #7
